title: Quanliang Ye
description: This is the personal site of Quanliang Ye
# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
# url: ""

url: https://yequanliang1993.github.io
search_enabled: false
google_analytics: G-4NR9BJ5YPK

aux_links:
  Template Repository: https://github.com/yequanliang1993/site_quanliang_ye

logo: Welcome visiting my personal site


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


math: katex