title: Quanliang Ye
description: This is the personal site of Quanliang Ye
# theme: just-the-docs

# url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/yequanliang1993/site_quanliang_ye

logo: "image/IMG_3768.jpeg"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

math: katex